apiVersion: v1
kind: Service
metadata:
  name: gopiadi-app-service
  labels:
    app: gopiadi-app
spec:
  selector:
    app: gopiadi-app  # This selector should match the label of the gopiadi/app pod
  ports:
    - protocol: TCP
      port: 80           # This is the port exposed by the service
      targetPort: 8080    # This is the port the container is listening on
  type: ClusterIP        # Default service type for internal cluster communication
