apiVersion: v1
kind: Service
metadata:
  name: vprocache01
  labels:
    app: vpromc
spec:
  selector:
    app: vpromc   # This must match the labels of the deployment
  ports:
    - protocol: TCP
      port: 11211  # The port the service will expose
      targetPort: 11211  # The port the container listens on
  type: ClusterIP  # Expose the service internally within the cluster
