apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
  labels:
    app: vpromc
spec:
  replicas: 1  # Number of replicas (adjust as needed)
  selector:
    matchLabels:
      app: vpromc
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
        - name: memcached
          image: memcached:latest  # Use the latest Memcached image
          ports:
            - containerPort: 11211  # Memcached default port
