apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce  # You can change this based on your use case
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
