apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672  # RabbitMQ default AMQP port
            - containerPort: 15672  # RabbitMQ management UI port
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user"  # Default user (can still be hardcoded)
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret  # Reference to the secret
                  key: rmq-pass     # The key inside the secret
