apiVersion: v1
kind: Service
metadata:
  name: vpromq01
  labels:
    app: vprormq
spec:
  selector:
    app: vprormq
  ports:
    - protocol: TCP
      port: 5672  # The port the service will expose for AMQP
      targetPort: 5672  # The port the container listens on for AMQ
  type: ClusterIP  # Expose the service internally within the cluster
