apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw==  # Make sure the password is base64 encoded
  rmq-pass: Z3Vlc3Q  # Make sure the password is base64 encoded
